#!/bin/bash

echo "Remove old files";
rm -rf `ls | grep -Evw 'pmaupdater|LICENSE-pmaupdater|README.md|.git|.gitignore'`

echo "Download new version from phpMyAdmin site" $PMALINK;
PMALINK=`wget -q -O - https://www.phpmyadmin.net/home_page/version.php | tail -n 1`
PMAVERSION=`wget -q -O - https://www.phpmyadmin.net/home_page/version.php | head -n 1`
wget -q $PMALINK

echo "Extract files";
sleep 1
unzip -q ./phpMyAdmin-$PMAVERSION-all-languages.zip -d .
mv ./phpMyAdmin-$PMAVERSION-all-languages/* .

echo "Setup config file and blowfish_secret";
cp ./config.sample.inc.php ./config.inc.php
PMABLOWFISH=`head -c 512 /dev/urandom | md5sum | awk '{print $1}'`
sed -i -- 's/\['\''blowfish_secret'\''\] = '\'''\''/\['\''blowfish_secret'\''\] = '\'''$PMABLOWFISH''\''/' ./config.inc.php

echo "Clean up"
rm -rf phpMyAdmin-*
PMABLOWFISH=
PMAVERSION=

echo "Done"
